# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ed80fb971693748d33c2e3229efe766"
name = "comix-qa-app"
# DÜZELTME: live -> livee (Çift 'e' yaptık)
application_url = "https://comix-qa-app-livee.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_products,write_metaobjects,read_metaobjects,write_metaobject_definitions,read_metaobject_definitions"

[auth]
# DÜZELTME: live -> livee
redirect_urls = [
  "https://comix-qa-app-livee.onrender.com/auth/callback",
  "https://comix-qa-app-livee.onrender.com/auth/shopify/callback",
  "https://comix-qa-app-livee.onrender.com/api/auth/callback"
]

[app_proxy]
# DÜZELTME: live -> livee
url = "https://comix-qa-app-livee.onrender.com/app/proxy"
subpath = "destek"
prefix = "apps"